name: Test

on:
  push: ~
  workflow_dispatch: ~

env:
  PHP_VERSION: '8.1'

jobs:
  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ env.PHP_VERSION }}"
          tools: composer:v2

      - name: Validate Composer
        run: composer validate --no-check-publish

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ env.PHP_VERSION }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ env.PHP_VERSION }}-composer-

      - name: Install PHP dependencies
        run: composer install --verbose --prefer-dist --no-progress --no-interaction --no-suggest --ignore-platform-reqs

      - name: Run PHP Coding Standard Checks
        run: vendor/bin/phpcs -s --standard=phpcs.xml

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run Psalm
        run: vendor/bin/psalm
